### ISSUE TITLE
Simple test with vitest and and vue-test-utils does not work

### ISSUE THREAD

**Issue by jonsalvas** [beholdr/maska#126]
### Describe the bug

When trying to write a test for a component using v-maska, it fails when trying to bind a simple data property to the v-model of a component that is annotated with v-maska directive. In live mode, everything works well, so it seems to be related to vue-test-utils or jsdom.

Error: 
```
TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at exports.convert (/Users/xxx/Projects/maskabug/node_modules/jsdom/lib/jsdom/living/generated/Event.js:22:9)
    at HTMLInputElement.dispatchEvent (/Users/xxx/Projects/maskabug/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:236:24)
    at C (file:///Users/xxx/Projects/maskabug/node_modules/maska/dist/maska.js:169:68)
    at Timeout._onTimeout (file:///Users/xxx/Projects/maskabug/node_modules/maska/dist/maska.js:187:5)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

### Reproduction link
https://github.com/jonsalvas/maskabug

### Maska Version

Error appears since upgrade to 2.0.0. Everything worked perfectly fine in 1.5.0

**Comment by beholdr** [comment]
When I have updated `vitest` in your repo to `0.28.3` test is passed.

**Comment by jonsalvas** [comment]
confirmed. Thanks for the support.
